# Generated by Django 4.0 on 2022-01-18 12:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 18, 12, 5, 1, 146721, tzinfo=utc), verbose_name='Date'),
        ),
    ]
