# Generated by Django 4.0 on 2022-01-19 06:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 19, 8, 8, 32, 605167), verbose_name='Date'),
        ),
    ]
