# Generated by Django 4.0 on 2022-01-19 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date',
        ),
        migrations.AddField(
            model_name='task',
            name='date_of_done',
            field=models.DateField(default=datetime.datetime(2022, 1, 19, 8, 14, 50, 654235), verbose_name='Date'),
        ),
    ]
